### PR TITLE
Use on-demand billing for Dynamo

### PR DESCRIPTION
**Pull request by jswny**
This should prevent pre-allocation of space to the tables since we want to pay per request instead.

### CODE REVIEW

**Comment by samcat116** [comment]
@cooperpellaton I'm not actually sure that on-demand is in the free tier. We might need to just set everything to 1GB.

**Comment by samcat116** [comment]
@jswny Let me fix the CI too

**Comment by cooperpellaton** [comment]
> @cooperpellaton I'm not actually sure that on-demand is in the free tier. We might need to just set everything to 1

I believe you’re correct. On demand is definitely cheaper than 5/5 but 1/1 _should_ be free tier capable.

**Comment by samcat116** [comment]
Free tier seems to go up to 25 WCUs and 25 RCUs. So we should make sure we stay under 25 to keep it free. I don't think well hit any of the storage or egress limits.

**Comment by cooperpellaton** [comment]
> Free tier seems to go up to 25 WCUs and 25 RCUs. So we should make sure we stay under 25 to keep it free. I don't think well hit any of the storage or egress limits.

But our old tables were at 5/5 and we were being charged so something isn’t right about the 25 limit.

**Comment by jswny** [comment]
Probably because there were like 10 tables so 10 * 5/5 = 50/50 pre-allocated.

**Comment by ironchefpython** [comment]
fix this or delet

**Comment by jswny** [comment]
> 
> 
> fix this or delet

I'll fix it if we still need it.

**Comment by jswny** [comment]
Clearly this is not needed.

**Pull request closed without merging**
